include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true

linter:
  rules:
    prefer_const_constructors: true 
    prefer_const_literals_to_create_immutables: true 
    prefer_const_declarations: true
    always_use_package_imports: true

custom_lint:
  rules:
    - avoid_returning_widgets