include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  language:
    strict-casts: true

linter:
  rules:
    prefer_const_constructors: true 
    prefer_const_literals_to_create_immutables: true 
    prefer_const_declarations: true

custom_lint:
  rules:
    - avoid_returning_widgets