import 'package:grimoji/config/emojis.dart';
import 'package:grimoji/config/levels/game_level.dart';

const List<GameLevel> chapter3Levels = [
  GameLevel(
    number: 29,
    timeLimit: 250,
    targetAmount: 3,
    targetEmoji: Emojis.biohazard,
    goal: 'Craft Acid Bombs to break through the iron gates',
    description: 'The Iron Gates - Learn Corrosive Magic',
    availableEmojis: [
      Emojis.snake,
      Emojis.rock,
      Emojis.leafyGreen,
      Emojis.droplet,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 30,
    timeLimit: 280,
    targetAmount: 10,
    targetEmoji: Emojis.brokenChain,
    goal: 'Use Acid to rust the chains and snap them',
    description: 'Bound by Chains - The fortress is sealed',
    availableEmojis: [
      Emojis.chains,
      Emojis.snake,
      Emojis.rock,
      Emojis.fire,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 31,
    timeLimit: 240,
    targetAmount: 5,
    targetEmoji: Emojis.metal,
    goal: 'Melt the shields into scrap metal',
    description: 'The Armory - Defend the keep',
    availableEmojis: [
      Emojis.shield,
      Emojis.snake,
      Emojis.chains,
      Emojis.fire,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 32,
    timeLimit: 300,
    targetAmount: 3,
    targetEmoji: Emojis.openLock,
    goal: 'Melt the padlocks to free the dungeon',
    description: 'The Locksmith - Secrets within',
    availableEmojis: [
      Emojis.chains,
      Emojis.snake,
      Emojis.skull,
      Emojis.droplet,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 33,
    timeLimit: 300,
    targetAmount: 2,
    targetEmoji: Emojis.volcano,
    goal: 'Craft Seismic Bombs to bring down the towers',
    description: 'Tremors - The earth awakens',
    availableEmojis: [
      Emojis.rock,
      Emojis.fire,
      Emojis.chains,
      Emojis.bone,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 34,
    timeLimit: 260,
    targetAmount: 15,
    targetEmoji: Emojis.debris,
    goal: 'Use Volcanoes to shatter the board',
    description: 'Crumbling Towers - The fortress falls',
    availableEmojis: [
      Emojis.mountain,
      Emojis.rock,
      Emojis.snake,
      Emojis.chains,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 35,
    timeLimit: 320,
    targetAmount: 5,
    targetEmoji: Emojis.ghost,
    goal: 'Free the ghosts from the dungeon',
    description: 'The Dungeon - Captives in chains',
    availableEmojis: [
      Emojis.locked,
      Emojis.snake,
      Emojis.bone,
      Emojis.fire,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 36,
    timeLimit: 280,
    targetAmount: 8,
    targetEmoji: Emojis.hole,
    goal: 'Burn holes in the floor with acid',
    description: 'Acid Rain - The siege begins',
    availableEmojis: [
      Emojis.snake,
      Emojis.cloud,
      Emojis.rock,
      Emojis.spider,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 37,
    timeLimit: 400,
    targetAmount: 1,
    targetEmoji: Emojis.crown,
    goal: 'Claim the fallen King\'s Crown',
    description: 'The Keep\'s Core - The final challenge',
    availableEmojis: [
      Emojis.crown,
      Emojis.locked,
      Emojis.chains,
      Emojis.snake,
      Emojis.rock,
      Emojis.fire,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 38,
    timeLimit: 260,
    targetAmount: 10,
    targetEmoji: Emojis.bat,
    goal: 'Craft bats from spiders',
    description: 'The Gargoyle\'s Perch - Night falls on the keep',
    availableEmojis: [
      Emojis.rock,
      Emojis.spider,
      Emojis.chains,
      Emojis.skull,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 39,
    timeLimit: 300,
    targetAmount: 5,
    targetEmoji: Emojis.brokenChain,
    goal: 'Use Acid to rust the chains and melt the locks',
    description: 'The Iron Maiden - Execution awaits',
    availableEmojis: [
      Emojis.chains,
      Emojis.locked,
      Emojis.snake,
      Emojis.fire,
      Emojis.rock,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 40,
    timeLimit: 280,
    targetAmount: 4,
    targetEmoji: Emojis.ghost,
    goal: 'Free the ghosts from the locked catacombs',
    description: 'The Catacombs - Ancient dead sleep below',
    availableEmojis: [
      Emojis.bone,
      Emojis.locked,
      Emojis.snake,
      Emojis.fire,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 41,
    timeLimit: 240,
    targetAmount: 12,
    targetEmoji: Emojis.biohazard,
    goal: 'Craft massive amounts of acid to cross the moat',
    description: 'Toxic Moat - The fortress\'s final defense',
    availableEmojis: [
      Emojis.snake,
      Emojis.droplet,
      Emojis.leafyGreen,
      Emojis.skull,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 42,
    timeLimit: 320,
    targetAmount: 4,
    targetEmoji: Emojis.volcano,
    goal: 'Master the Earthquake magic to bring down the inner keep',
    description: 'Tremors II - The earth shakes with fury',
    availableEmojis: [
      Emojis.rock,
      Emojis.chains,
      Emojis.mountain,
      Emojis.fire,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 43,
    timeLimit: 300,
    targetAmount: 3,
    targetEmoji: Emojis.derelictHouse,
    goal: 'Destroy the abandoned guard tower',
    description: 'The Derelict House - Ruins within ruins',
    availableEmojis: [
      Emojis.rock,
      Emojis.chains,
      Emojis.bone,
      Emojis.spider,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 44,
    timeLimit: 280,
    targetAmount: 20,
    targetEmoji: Emojis.debris,
    goal: 'Use Volcanoes to bring down the derelict house',
    description: 'Shattered Foundations - The keep collapses',
    availableEmojis: [
      Emojis.derelictHouse,
      Emojis.rock,
      Emojis.fire,
      Emojis.cloud,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 45,
    timeLimit: 260,
    targetAmount: 5,
    targetEmoji: Emojis.coin,
    goal: 'Loot the keep and melt metal into coins',
    description: 'The King\'s Ransom - Treasure awaits',
    availableEmojis: [
      Emojis.metal,
      Emojis.fire,
      Emojis.locked,
      Emojis.snake,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 46,
    timeLimit: 300,
    targetAmount: 3,
    targetEmoji: Emojis.crocodile,
    goal: 'Craft crocodiles from snakes',
    description: 'Dragon Scales - The dragon awakens',
    availableEmojis: [
      Emojis.snake,
      Emojis.rock,
      Emojis.leafyGreen,
      Emojis.droplet,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 47,
    timeLimit: 350,
    targetAmount: 6,
    targetEmoji: Emojis.volcano,
    goal: 'Total destruction with seismic bombs',
    description: 'The Keep Collapses - All hands on deck',
    availableEmojis: [
      Emojis.rock,
      Emojis.derelictHouse,
      Emojis.locked,
      Emojis.snake,
      Emojis.chains,
    ],
    type: LevelType.puzzle,
  ),

  GameLevel(
    number: 48,
    timeLimit: 500,
    targetAmount: 1,
    targetEmoji: Emojis.dragon,
    goal: 'Summon the ultimate dragon from snakes',
    description: 'The Ruined King\'s Pet - The final boss',
    availableEmojis: [
      Emojis.snake,
      Emojis.crocodile,
      Emojis.rock,
      Emojis.chains,
      Emojis.fire,
    ],
    type: LevelType.puzzle,
  ),
];