name: Recover Keystore

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Write keystore and print fingerprint
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
          keytool -list -v -keystore keystore.jks -storepass "${{ secrets.STORE_PASSWORD }}" -alias "${{ secrets.KEY_ALIAS }}" | grep -E "SHA1|SHA-1|Alias name"
      - uses: actions/upload-artifact@v4
        with:
          name: keystore-recovery
          path: |
            keystore.jks
          retention-days: 1
