name: Recover Keystore

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Write keystore artifact
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" > keystore.b64
      - uses: actions/upload-artifact@v4
        with:
          name: keystore-recovery
          path: keystore.b64
          retention-days: 1
